# Generated by Django 2.2.4 on 2019-08-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContracOfNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrac_of_number', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'Останній номер договору',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.IntegerField(blank=True, default=None, null=True)),
                ('entity_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('second_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patronymic', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('value_added_tax', models.IntegerField(blank=True, default=None, null=True)),
                ('single_tax', models.BooleanField(blank=True, default=False, null=True)),
                ('general_tax', models.BooleanField(blank=True, default=False, null=True)),
                ('extract', models.BooleanField(blank=True, default=False, null=True)),
                ('passport', models.BooleanField(blank=True, default=False, null=True)),
                ('contract_number', models.IntegerField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('license', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customers')),
            ],
            options={
                'verbose_name': 'Адреса',
                'verbose_name_plural': 'Адреси',
            },
        ),
    ]
